In [14]:
import torch
from torch.utils.data import Dataset, DataLoader

class HeightWeightDataset(Dataset):
    def __init__(self, csv_path):
        self.data = []
        with open(csv_path, 'r', encoding='utf-8') as f:
            next(f) # 첫 컬럼 헤더 무시 
            for line in f:
                # print(line) # 1, 65.78, 112.99
                
                _, height, weight = line.strip().split(",") # _: index, 각각 언패킹
                # TypeError: float() argument must be a string or a real number, not 'list'
                # 여기서 바로 float 사용할 수 없는 이유 list형태가 아니여서 
                # print(height, weight) # 65.78  112.99
                
                height = float(height)
                weight = float(weight)
                # print(height, weight) # 65.78 112.99
                
                convert_to_kg_data = round(self.convert_to_kg(weight), 2)
                convert_to_cm_data = round(self.inch_to_cm(height), 1)
                # print(convert_to_cm_data, convert_to_kg_data) # 167.1 51.25
                self.data.append([convert_to_cm_data, convert_to_kg_data])

    def __getitem__(self, index):
        data = torch.tensor(self.data[index], dtype=torch.float) # dataloader에 올리기 위해 tensor 형태로 바꾸고 리턴 
        return data

    def __len__(self):
        return len(self.data)

    def convert_to_kg(self, weight_lb):
        return weight_lb * 0.453592
    
    def inch_to_cm(self, inch):
        return inch * 2.54
    
    # convert_to_kg, inch_to_cm으로 나눈 이유는 
    # init에서 복잡하게 표현되기 때문에 함수로 선언 하고 init에서 정의


if __name__ == "__main__":
    dataset = HeightWeightDataset("./hw_200.csv")
    dataloader = DataLoader(dataset, batch_size = 1, shuffle=True)

    for batch in dataloader:
        x = batch[:, 0].unsqueeze(1) # [] 텐서의 깊이, 차원 승격
        y = batch[:, 1].unsqueeze(1) 
        # print(x, y) # tensor([[176.2000]]) tensor([[63.0700]])

tensor([[174.5000]]) tensor([[59.3100]])
tensor([[180.9000]]) tensor([[62.5500]])
tensor([[174.4000]]) tensor([[64.8500]])
tensor([[163.8000]]) tensor([[51.2100]])
tensor([[178.3000]]) tensor([[65.7700]])
tensor([[187.5000]]) tensor([[63.1900]])
tensor([[182.4000]]) tensor([[63.5500]])
tensor([[165.8000]]) tensor([[58.6500]])
tensor([[177.6000]]) tensor([[66.6900]])
tensor([[174.8000]]) tensor([[62.1000]])
tensor([[175.]]) tensor([[52.3800]])
tensor([[175.5000]]) tensor([[61.2000]])
tensor([[165.9000]]) tensor([[52.5800]])
tensor([[176.4000]]) tensor([[58.2500]])
tensor([[178.3000]]) tensor([[54.9400]])
tensor([[174.3000]]) tensor([[61.0700]])
tensor([[173.1000]]) tensor([[61.9400]])
tensor([[166.7000]]) tensor([[55.9200]])
tensor([[177.2000]]) tensor([[61.7200]])
tensor([[172.6000]]) tensor([[56.3400]])
tensor([[177.3000]]) tensor([[64.1800]])
tensor([[168.9000]]) tensor([[57.8100]])
tensor([[169.9000]]) tensor([[66.0800]])
tensor([[178.4000]]) tensor([[64.1800]])
tensor([[170.5000]])